sudo: required

language: node

services:
  - docker

branches:
  only:
  - master

jobs:
  include:
    - stage: invoicing-api-backend-flowz
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t invoicing_api_backend_flowz:"$DOCKER_IMAGE_TAG" .
      - docker images
      - docker tag invoicing_api_backend_flowz:"$DOCKER_IMAGE_TAG" $DOCKER_USERNAME/invoicing_api_backend_flowz:"$DOCKER_IMAGE_TAG"
      - docker push $DOCKER_USERNAME/invoicing_api_backend_flowz:"$DOCKER_IMAGE_TAG"
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - npaul@officebrain.com
                        - kdalsania@officebrain.com
                        - hdheniya@officebrain.com
                        - dweepp@officebrain.com
    on_success: always
    on_failure: always       
