sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - QA

jobs:
  include:
    - stage: invoicing-api-backend-flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t invoicing_api_backend_flowz:latest .;
            docker images;
            docker tag invoicing_api_backend_flowz:latest $DOCKER_USERNAME_FLOWZ/invoicing_api_backend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/invoicing_api_backend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t invoicing_api_backend_flowz:dev .;
            docker images;
            docker tag invoicing_api_backend_flowz:dev $DOCKER_USERNAME/invoicing_api_backend_flowz:dev;
            docker push $DOCKER_USERNAME/invoicing_api_backend_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t invoicing_api_backend_flowz:staging .;
            docker tag invoicing_api_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/invoicing_api_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag invoicing_api_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/invoicing_api_backend_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/invoicing_api_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/invoicing_api_backend_flowz:staging;    
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t invoicing_api_backend_flowz:qa .;
            docker images;
            docker tag invoicing_api_backend_flowz:qa $DOCKER_USERNAME/invoicing_api_backend_flowz:qa;
            docker push $DOCKER_USERNAME/invoicing_api_backend_flowz:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - npaul@officebrain.com
      - kdalsania@officebrain.com
      - hdheniya@officebrain.com
      - dweepp@officebrain.com
    on_success: always
    on_failure: always
